avoid-breaking-exported-api = false
allowed-idents-below-min-chars = [ "x", "y", "z", "r", "g", "b", "c", "s" ]
absolute-paths-allowed-crates = [ "cstree" ]
allowed-wildcard-imports      = [ "super", "Kind" ]
