name: Rust Documentation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Test with Cargo"]  # must match the `name:` of rust.yml exactly
    types:
      - completed

permissions:
  contents: write

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  CARGO_TERM_COLOR: always

jobs:
  pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Restore Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false
          cache-on-failure: true

      - name: Build Rust Documentation
        run: |
          # Build documentation for public workspace members.
          # See:
          #  <https://doc.rust-lang.org/rustdoc/scraped-examples.html>
          cargo doc --workspace --exclude xtask --no-deps \
            --document-private-items -Zunstable-options -Zrustdoc-scrape-examples

      - name: Prepare GitHub Pages Deployment
        run: |
          # By default the generated documentation will not have an index page.
          # This makes it so that when we visit ndg.feel-co.org it takes us to
          # the API documentation found in the ndg-commonmark section
          mkdir -p ./target/doc
          echo '<meta http-equiv="Refresh" content="0; url=ndg_commonmark" />' > ./target/doc/index.html

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./target/doc
          branch: gh-pages
          clean: false # keep existing files, i.e., badges

