name: Rust Documentation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Test with Cargo"]  # must match the `name:` of rust.yml exactly
    types:
      - completed

permissions:
  contents: write

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  CARGO_TERM_COLOR: always

jobs:
  pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Restore Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false
          cache-on-failure: true

      - name: Build Rust Documentation
        run: |
          # Build documentation for public workspace members.
          # See:
          #  <https://doc.rust-lang.org/rustdoc/scraped-examples.html>
          cargo doc --workspace --exclude xtask --no-deps \
            --document-private-items -Zunstable-options -Zrustdoc-scrape-examples

      - name: Build NDG Binary
        run: cargo build --release -p ndg

      - name: Generate NDG Documentation
        run: |
          # Generate NDG's own documentation using NDG itself
          ./target/release/ndg html --config .github/ndg.toml

      - name: Prepare GitHub Pages Deployment
        run: |
          # - ndg.feel-co.org/     -> NDG user documentation
          # - ndg.feel-co.org/api/ -> Rustdoc API documentation
          mkdir -p ./deploy

          mv ./build/* ./deploy/
          mv ./target/doc ./deploy/api

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./deploy
          branch: gh-pages
          clean: false # keep existing files, i.e., badges

